# name: verify Dependabot PR for any dependency update

# on:
#   pull_request:
#     branches:
#       - 'main'

# permissions:
#   pull-requests: write
#   contents: write

# jobs:
#   check-dependabot:
#     runs-on: ubuntu-latest
#     if: github.actor == 'dependabot[bot]'
#     outputs:
#       DEPENDENCY_UPDATED: ${{ steps.check-dep.outputs.DEPENDENCY_UPDATED }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Dependabot metadata
#         id: metadata
#         uses: dependabot/fetch-metadata@v1.5.0
#         with:
#           github-token: "${{ secrets.DEPENDABOT_GITHUB_TOKEN }}"
          
#       - name: Check if any dependency is updated
#         id: check-dep
#         run: |
#           for dep in $(cat package.json | jq -r '.dependencies, .devDependencies | keys[]')
#           do
#             if echo "${{ steps.metadata.outputs.dependency-names }}" | grep -q "$dep"; then
#               echo "DEPENDENCY_UPDATED=$dep" >> $GITHUB_ENV
#               exit 0
#             fi
#           done
#           echo "DEPENDENCY_UPDATED=none" >> $GITHUB_ENV

#   test:
#     needs: check-dependabot
#     if: needs.check-dependabot.outputs.DEPENDENCY_UPDATED != 'none'
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x]
#     steps:
#       - name: Checkout test
#         uses: actions/checkout@v4
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - name: npm ci
#         run: npm ci
#       - name: Run tests
#         run: npm test -- -u
